configpath: 
  logdir1: "../logdir1/log.txt"
  logdir2: "../logdir2/log.txt"
  logdir3: "../logdir3/log.txt"

etcd:
  addr: "localhost:2379"
  logkeys:
    - "/logs/logdir1"
    - "/logs/logdir2"
    - "/logs/logdir3"

kafka:
  brokers:
    - "localhost:9092"
  topic: "logcatchsys"

consumer:
  group: "elasticsearch-worker"

elasticsearch:
  addr: "http://localhost:9200"
  index: "logs"